the_dict = {
    "home_team": [],
    "visit_team": [],
    "date": [],
    "city": [],
    "country": [],
    "stadium": [],
    "tournament": [],
    "public": [],
    "fouls_home_first_time": [],
    "fouls_home_second_time": [],
    "fouls_visit_first_time": [],
    "fouls_visit_second_time": [],
    "conner_home_first_time": [],       
    "conner_home_second_time": [],
    "conner_visit_first_time": [],
    "conner_visit_second_time": [],
    "shots_block_home_first_time": [],
    "shots_block_home_second_time": [],
    "shots_block_visit_first_time": [],
    "shots_block_visit_second_time": [],
    "lost_opportunity_home_first_time": [],
    "lost_opportunity_home_second_time": [],
    "lost_opportunity_visit_first_time": [],
    "lost_opportunity_visit_second_time": [],
    "kick_saved_home_first_time": [],
    "kick_saved_home_second_time": [],
    "kick_saved_visit_first_time": [],
    "kick_saved_visit_second_time": [],
    "offside_home_first_time": [],
    "offside_home_second_time": [],
    "offside_visit_first_time": [],
    "offside_visit_second_time": [],

}